// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  AuthRequestDto,
  BanUserRequest,
  ChangeEmailRequest,
  ChangePasswordRequest,
  OAuthRequest,
  RefreshTokenRequest,
  RegisterRequest,
  ResetPasswordRequest,
  SendOtpRequest,
  TokenResponseDto,
  VerifyEmailRequest,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── AuthService ──────────────────────────────────────────────
export const AuthService = {

  async unbanUser({ userId }: { userId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/auth/${userId}/unban`, undefined, config);
    return data;
  },

  async banUser({ userId, body }: { userId: string; body: BanUserRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/auth/${userId}/ban`, body, config);
    return data;
  },

  async verifyOtp({ body }: { body: VerifyEmailRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/verify-otp', body, config);
    return data;
  },

  async resendOtp({ body }: { body: SendOtpRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/send-otp', body, config);
    return data;
  },

  async sendChangeEmailOtp({ body }: { body: SendOtpRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/send-change-email-otp', body, config);
    return data;
  },

  async resetPassword({ body }: { body: ResetPasswordRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/reset-password', body, config);
    return data;
  },

  async register({ body }: { body: RegisterRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/register', body, config);
    return data;
  },

  async refreshToken({ body }: { body: RefreshTokenRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<TokenResponseDto>> {
    const { data } = await api.post('/api/v1/auth/refresh-token', body, config);
    return data;
  },

  async login({ body }: { body: AuthRequestDto }, config?: AxiosRequestConfig): Promise<ApiResponse<TokenResponseDto>> {
    const { data } = await api.post('/api/v1/auth/login', body, config);
    return data;
  },

  async loginWithGoogle({ body }: { body: OAuthRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<TokenResponseDto>> {
    const { data } = await api.post('/api/v1/auth/login/google', body, config);
    return data;
  },

  async changePassword({ body }: { body: ChangePasswordRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/change-password', body, config);
    return data;
  },

  async changeEmail({ body }: { body: ChangeEmailRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/auth/change-email', body, config);
    return data;
  },
};