// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  PaginatedApiResponse,
} from '@/types';
import type {
  AdminCourseStatisticsOverviewResponse,
  ArticleLessonResponse,
  AssignmentLessonResponse,
  CategoryResponse,
  CourseCurriculumResponse,
  CourseResponse,
  CreateArticleLessonRequest,
  CreateAssignmentLessonRequest,
  CreateCategoryRequest,
  CreateCourseImageRequest,
  CreateCourseRequest,
  CreateLessonRequest,
  CreateQuizLessonRequest,
  CreateQuizQuestionRequest,
  CreateSectionRequest,
  CreateSubtitleTrackRequest,
  CreateVideoLessonRequest,
  CreateVideoQuestionRequest,
  InstructorCourseStatisticsOverviewResponse,
  InstructorCourseSummaryResponse,
  LessonPositionResponse,
  LessonResponse,
  MoveLessonRequest,
  MoveSectionRequest,
  QuizLessonResponse,
  QuizQuestionResponse,
  RejectCourseRequest,
  RejectCourseResponse,
  SectionPositionResponse,
  SectionResponse,
  SubtitleTrackResponse,
  SyncQuizRequest,
  UpdateArticleLessonRequest,
  UpdateAssignmentLessonRequest,
  UpdateCategoryRequest,
  UpdateCourseImageRequest,
  UpdateCourseRequest,
  UpdateLessonRequest,
  UpdateQuizLessonRequest,
  UpdateQuizQuestionRequest,
  UpdateSectionRequest,
  UpdateSubtitleTrackRequest,
  UpdateVideoLessonRequest,
  UpdateVideoQuestionRequest,
  VideoLessonResponse,
  VideoQuestionResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── CourseService ──────────────────────────────────────────────
export const CourseService = {

  async getCourseById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}`, config);
    return data;
  },

  async updateCourse({ id, body }: { id: string; body: UpdateCourseRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.put(`/api/v1/courses/${id}`, body, config);
    return data;
  },

  async getAllCourses({ page, size, query, sort, rating, priceFrom, priceTo, categoryId, instructorId }: { page?: number; size?: number; query?: string; sort?: string; rating?: number; priceFrom?: number; priceTo?: number; categoryId?: string; instructorId?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CourseResponse>> {
    const { data } = await api.get('/api/v1/courses', { params: { page, size, query, sort, rating, priceFrom, priceTo, categoryId, instructorId }, ...config });
    return data;
  },

  async createCourse({ body }: { body: CreateCourseRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post('/api/v1/courses', body, config);
    return data;
  },

  /** Unarchive course */
  async unarchiveCourse({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post(`/api/v1/courses/${id}/unarchive`, undefined, config);
    return data;
  },

  /** Submit course for approval */
  async submitCourse({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post(`/api/v1/courses/${id}/submit`, undefined, config);
    return data;
  },

  /** Archive course */
  async archiveCourse({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post(`/api/v1/courses/${id}/archive`, undefined, config);
    return data;
  },

  /** Move editable course section */
  async moveSection({ id, sectionId, body }: { id: string; sectionId: string; body: MoveSectionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<SectionPositionResponse>> {
    const { data } = await api.patch(`/api/v1/courses/${id}/curriculum/sections/${sectionId}/position`, body, config);
    return data;
  },

  /** Move editable course lesson */
  async moveLesson({ id, lessonId, body }: { id: string; lessonId: string; body: MoveLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<LessonPositionResponse>> {
    const { data } = await api.patch(`/api/v1/courses/${id}/curriculum/lessons/${lessonId}/position`, body, config);
    return data;
  },

  async getRejectReason({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<RejectCourseResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/reject-reason`, config);
    return data;
  },

  /** Get owned published course snapshot */
  async getPublishedSnapshot({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/published`, config);
    return data;
  },

  /** Get owned published course curriculum snapshot */
  async getPublishedSnapshotCurriculum({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/published/curriculum`, config);
    return data;
  },

  /** Get enrolled course */
  async getEnrolledCourseById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/enrolled`, config);
    return data;
  },

  /** Get enrolled course curriculum */
  async getEnrolledCurriculum({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/enrolled/curriculum`, config);
    return data;
  },

  /** Get editable course draft */
  async getCourseDraft({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/draft`, config);
    return data;
  },

  /** Get editable course curriculum */
  async getDraftCurriculum({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/draft/curriculum`, config);
    return data;
  },

  async getPublishedCurriculum({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/courses/${id}/curriculum`, config);
    return data;
  },

  /** Get my courses */
  async getMyCourses({ page, size, query, sort, rating, priceFrom, priceTo, status, publishStatus, categoryId }: { page?: number; size?: number; query?: string; sort?: string; rating?: number; priceFrom?: number; priceTo?: number; status?: string; publishStatus?: string; categoryId?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CourseResponse>> {
    const { data } = await api.get('/api/v1/courses/mine', { params: { page, size, query, sort, rating, priceFrom, priceTo, status, publishStatus, categoryId }, ...config });
    return data;
  },

  async getCourseById_1({ ids }: { ids: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse[]>> {
    const { data } = await api.get('/api/v1/courses/ids', { params: { ids }, ...config });
    return data;
  },
};

// ── SectionService ──────────────────────────────────────────────
export const SectionService = {

  async updateSection({ courseId, sectionId, body }: { courseId: string; sectionId: string; body: UpdateSectionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<SectionResponse>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/sections/${sectionId}`, body, config);
    return data;
  },

  async deleteSection({ courseId, sectionId }: { courseId: string; sectionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/sections/${sectionId}`, config);
    return data;
  },

  async createSection({ courseId, body }: { courseId: string; body: CreateSectionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<SectionResponse>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/sections`, body, config);
    return data;
  },
};

// ── LessonService ──────────────────────────────────────────────
export const LessonService = {

  async updateLesson({ courseId, sectionId, lessonId, body }: { courseId: string; sectionId: string; lessonId: string; body: UpdateLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<LessonResponse>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/sections/${sectionId}/lessons/${lessonId}`, body, config);
    return data;
  },

  async deleteLesson({ courseId, sectionId, lessonId }: { courseId: string; sectionId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/sections/${sectionId}/lessons/${lessonId}`, config);
    return data;
  },

  async createLesson({ courseId, sectionId, body }: { courseId: string; sectionId: string; body: CreateLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<LessonResponse>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/sections/${sectionId}/lessons`, body, config);
    return data;
  },
};

// ── VideoLessonService ──────────────────────────────────────────────
export const VideoLessonService = {

  async getVideoByLessonId({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoLessonResponse>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos`, config);
    return data;
  },

  async updateVideoLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: UpdateVideoLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos`, body, config);
    return data;
  },

  async createVideoLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateVideoLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos`, body, config);
    return data;
  },
};

// ── SubtitleTrackService ──────────────────────────────────────────────
export const SubtitleTrackService = {

  async updateSubtitle({ courseId, lessonId, subtitleId, body }: { courseId: string; lessonId: string; subtitleId: string; body: UpdateSubtitleTrackRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<SubtitleTrackResponse>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/subtitles/${subtitleId}`, body, config);
    return data;
  },

  async deleteSubtitle({ courseId, lessonId, subtitleId }: { courseId: string; lessonId: string; subtitleId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/subtitles/${subtitleId}`, config);
    return data;
  },

  async getSubtitles({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<SubtitleTrackResponse[]>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/subtitles`, config);
    return data;
  },

  async createSubtitle({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateSubtitleTrackRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<SubtitleTrackResponse>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/subtitles`, body, config);
    return data;
  },
};

// ── VideoQuestionService ──────────────────────────────────────────────
export const VideoQuestionService = {

  async getQuestionById({ courseId, lessonId, id }: { courseId: string; lessonId: string; id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoQuestionResponse>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/questions/${id}`, config);
    return data;
  },

  async updateQuestion({ courseId, lessonId, id, body }: { courseId: string; lessonId: string; id: string; body: UpdateVideoQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoQuestionResponse>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/questions/${id}`, body, config);
    return data;
  },

  async deleteQuestion({ courseId, lessonId, id }: { courseId: string; lessonId: string; id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/questions/${id}`, config);
    return data;
  },

  async getQuestionsByLessonId({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoQuestionResponse[]>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/questions`, config);
    return data;
  },

  async createQuestion({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateVideoQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoQuestionResponse>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/videos/questions`, body, config);
    return data;
  },
};

// ── QuizLessonService ──────────────────────────────────────────────
export const QuizLessonService = {

  async getQuizByLessonId({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizLessonResponse>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes`, config);
    return data;
  },

  /** Update quiz (no questions) */
  async updateQuizSettings({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: UpdateQuizLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes`, body, config);
    return data;
  },

  /** Create quiz with initial questions */
  async createQuizLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateQuizLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes`, body, config);
    return data;
  },

  /** Sync quiz changes to learning service (with optional regrade trigger) */
  async syncQuiz({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: SyncQuizRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes/sync`, body, config);
    return data;
  },
};

// ── QuizQuestionService ──────────────────────────────────────────────
export const QuizQuestionService = {

  /** Update a question (options use merge strategy: id→update, no id→create, missing→delete) */
  async updateQuestion_1({ lessonId, questionId, courseId, body }: { lessonId: string; questionId: string; courseId: string; body: UpdateQuizQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizQuestionResponse>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes/questions/${questionId}`, body, config);
    return data;
  },

  /** Delete a question (blocked if it would violate numberOfQuestionPerQuizSession) */
  async deleteQuestion_1({ lessonId, questionId, courseId }: { lessonId: string; questionId: string; courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes/questions/${questionId}`, config);
    return data;
  },

  /** List all questions for a quiz */
  async getQuestions({ lessonId, courseId }: { lessonId: string; courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizQuestionResponse[]>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes/questions`, config);
    return data;
  },

  /** Add a question to a quiz */
  async addQuestion({ lessonId, courseId, body }: { lessonId: string; courseId: string; body: CreateQuizQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizQuestionResponse>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/quizzes/questions`, body, config);
    return data;
  },
};

// ── AssignmentLessonService ──────────────────────────────────────────────
export const AssignmentLessonService = {

  async getAssigmentByLessonId({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<AssignmentLessonResponse>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/assignments`, config);
    return data;
  },

  async updateAssigmentLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: UpdateAssignmentLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/assignments`, body, config);
    return data;
  },

  async createAssigmentLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateAssignmentLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/assignments`, body, config);
    return data;
  },
};

// ── ArticleLessonService ──────────────────────────────────────────────
export const ArticleLessonService = {

  async getArticleByLessonId({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<ArticleLessonResponse>> {
    const { data } = await api.get(`/api/v1/courses/${courseId}/lessons/${lessonId}/articles`, config);
    return data;
  },

  async updateArticleLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: UpdateArticleLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/lessons/${lessonId}/articles`, body, config);
    return data;
  },

  async createArticleLesson({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateArticleLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/lessons/${lessonId}/articles`, body, config);
    return data;
  },
};

// ── CourseImageService ──────────────────────────────────────────────
export const CourseImageService = {

  async updateCourseImage({ imageId, courseId, body }: { imageId: string; courseId: string; body: UpdateCourseImageRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/courses/${courseId}/images/${imageId}`, body, config);
    return data;
  },

  async deleteCourseImage({ imageId, courseId }: { imageId: string; courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/courses/${courseId}/images/${imageId}`, config);
    return data;
  },

  async uploadCourseImages({ courseId, body }: { courseId: string; body: CreateCourseImageRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/courses/${courseId}/images`, body, config);
    return data;
  },
};

// ── CategoryService ──────────────────────────────────────────────
export const CategoryService = {

  async updateCategory({ id, body }: { id: string; body: UpdateCategoryRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/categories/${id}`, body, config);
    return data;
  },

  async getAllCategories(config?: AxiosRequestConfig): Promise<ApiResponse<CategoryResponse[]>> {
    const { data } = await api.get('/api/v1/categories', config);
    return data;
  },

  async createCategory({ body }: { body: CreateCategoryRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/categories', body, config);
    return data;
  },
};

// ── AdminCourseService ──────────────────────────────────────────────
export const AdminCourseService = {

  async rejectCourse({ id, body }: { id: string; body: RejectCourseRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post(`/api/v1/admin/courses/${id}/reject`, body, config);
    return data;
  },

  async approveCourse({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.post(`/api/v1/admin/courses/${id}/approve`, undefined, config);
    return data;
  },

  async replayRecommendationEvents(config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/admin/courses/recommendation/replay', undefined, config);
    return data;
  },

  async getAllCourses_1({ page, size, query, sort, rating, priceFrom, priceTo, status, publishStatus, categoryId, instructorId }: { page?: number; size?: number; query?: string; sort?: string; rating?: number; priceFrom?: number; priceTo?: number; status?: string; publishStatus?: string; categoryId?: string; instructorId?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CourseResponse>> {
    const { data } = await api.get('/api/v1/admin/courses', { params: { page, size, query, sort, rating, priceFrom, priceTo, status, publishStatus, categoryId, instructorId }, ...config });
    return data;
  },

  async getCourseById_2({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/admin/courses/${id}`, config);
    return data;
  },

  async getCourseDraft_1({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseResponse>> {
    const { data } = await api.get(`/api/v1/admin/courses/${id}/draft`, config);
    return data;
  },

  async getDraftCurriculum_1({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/admin/courses/${id}/draft/curriculum`, config);
    return data;
  },

  async getCourseCurriculum({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseCurriculumResponse>> {
    const { data } = await api.get(`/api/v1/admin/courses/${id}/curriculum`, config);
    return data;
  },
};

// ── CourseStatisticsService ──────────────────────────────────────────────
export const CourseStatisticsService = {

  /** Get my course statistics overview */
  async getInstructorOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorCourseStatisticsOverviewResponse>> {
    const { data } = await api.get('/api/v1/courses/mine/statistics/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },

  /** Get admin course statistics overview */
  async getAdminOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<AdminCourseStatisticsOverviewResponse>> {
    const { data } = await api.get('/api/v1/admin/courses/statistics/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },
};

// ── AdminInstructorService ──────────────────────────────────────────────
export const AdminInstructorService = {

  async getCourseSummary({ instructorId }: { instructorId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorCourseSummaryResponse>> {
    const { data } = await api.get(`/api/v1/admin/instructors/${instructorId}/course-summary`, config);
    return data;
  },
};
