// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  PaginatedApiResponse,
} from '@/types';
import type {
  AdminOverviewResponse,
  CheckEnrollmentStatus,
  CourseStatisticsResponse,
  CreateOrderRequest,
  CreateVoucherRequest,
  DashboardMetricsResponse,
  EnrolledCourseResponse,
  InstructorRevenueResponse,
  InstructorStatisticsResponse,
  OrderDetailResponse,
  UpdatePaymentMethodRequest,
  UpdateVoucherRequest,
  UserEnrollmentSummaryResponse,
  VoucherResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── VoucherService ──────────────────────────────────────────────
export const VoucherService = {

  async getVoucherById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VoucherResponse>> {
    const { data } = await api.get(`/api/v1/vouchers/${id}`, config);
    return data;
  },

  async updateVoucher({ id, body }: { id: string; body: UpdateVoucherRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/vouchers/${id}`, body, config);
    return data;
  },

  async deleteVoucher({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/vouchers/${id}`, config);
    return data;
  },

  async getVouchers({ page, size, query, sort }: { page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<VoucherResponse>> {
    const { data } = await api.get('/api/v1/vouchers', { params: { page, size, query, sort }, ...config });
    return data;
  },

  async createVoucher({ body }: { body: CreateVoucherRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/vouchers', body, config);
    return data;
  },

  async getVoucherByCode({ code }: { code: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VoucherResponse>> {
    const { data } = await api.get('/api/v1/vouchers/code', { params: { code }, ...config });
    return data;
  },
};

// ── OrderService ──────────────────────────────────────────────
export const OrderService = {

  async updatePaymentMethod({ orderId, body }: { orderId: string; body: UpdatePaymentMethodRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.put(`/api/v1/orders/${orderId}/payment-method`, body, config);
    return data;
  },

  async cancelOrder({ orderId }: { orderId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.put(`/api/v1/orders/${orderId}/cancel`, undefined, config);
    return data;
  },

  async getOrders({ page, size, query, sort }: { page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<OrderDetailResponse>> {
    const { data } = await api.get('/api/v1/orders', { params: { page, size, query, sort }, ...config });
    return data;
  },

  async createOrder({ body }: { body: CreateOrderRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.post('/api/v1/orders', body, config);
    return data;
  },

  async getOrderById({ orderId }: { orderId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.get(`/api/v1/orders/${orderId}`, config);
    return data;
  },

  /** Get orders by user id for admin */
  async getOrdersByUserIdForAdmin({ userId, page, size, query, sort }: { userId: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<OrderDetailResponse>> {
    const { data } = await api.get(`/api/v1/orders/admin/users/${userId}`, { params: { page, size, query, sort }, ...config });
    return data;
  },
};

// ── EnrollmentService ──────────────────────────────────────────────
export const EnrollmentService = {

  async checkEnrollmentStatus({ body }: { body: string[] }, config?: AxiosRequestConfig): Promise<ApiResponse<CheckEnrollmentStatus[]>> {
    const { data } = await api.post('/api/v1/enrollments/check', body, config);
    return data;
  },

  async getEnrolledCourses({ page, size }: { page?: number; size?: number }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<EnrolledCourseResponse>> {
    const { data } = await api.get('/api/v1/enrollments', { params: { page, size }, ...config });
    return data;
  },
};

// ── StatisticsService ──────────────────────────────────────────────
export const StatisticsService = {

  /** Get instructor statistics */
  async getInstructorOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorStatisticsResponse>> {
    const { data } = await api.get('/api/v1/statistics/instructor/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },

  /** Get course specific statistics overview */
  async getCourseStatisticsOverview({ courseId, groupBy, startDate, endDate }: { courseId: string; groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseStatisticsResponse>> {
    const { data } = await api.get(`/api/v1/statistics/instructor/courses/${courseId}/overview`, { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },

  /** Get dashboard metrics */
  async getDashboardMetrics({ year, month }: { year?: number; month?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<DashboardMetricsResponse>> {
    const { data } = await api.get('/api/v1/statistics/dashboard', { params: { year, month }, ...config });
    return data;
  },

  /** Get admin overview */
  async getAdminOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<AdminOverviewResponse>> {
    const { data } = await api.get('/api/v1/statistics/admin/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },

  /** Get admin instructor revenue series */
  async getInstructorRevenueSeries({ instructorId, groupBy, startDate, endDate }: { instructorId: string; groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorRevenueResponse>> {
    const { data } = await api.get(`/api/v1/statistics/admin/instructors/${instructorId}/revenue/series`, { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },
};

// ── AdminEnrollmentService ──────────────────────────────────────────────
export const AdminEnrollmentService = {

  async getUserSummary({ userId }: { userId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserEnrollmentSummaryResponse>> {
    const { data } = await api.get(`/api/v1/enrollments/admin/users/${userId}/summary`, config);
    return data;
  },
};
