// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  AdminOverviewResponse,
  ApiResponse,
  CheckEnrollmentStatus,
  CourseResponse,
  CourseStatisticsResponse,
  CreateOrderRequest,
  CreateVoucherRequest,
  DashboardMetricsResponse,
  InstructorRevenueResponse,
  InstructorStatisticsResponse,
  OrderDetailResponse,
  OrderResponse,
  PaginatedApiResponse,
  UpdateVoucherRequest,
  UserEnrollmentSummaryResponse,
  VoucherResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── VoucherService ──────────────────────────────────────────────
export const VoucherService = {

  async getVoucherById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VoucherResponse>> {
    const { data } = await api.get(`/api/v1/vouchers/${id}`, config);
    return data;
  },

  async updateVoucher({ id, body }: { id: string; body: UpdateVoucherRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/vouchers/${id}`, body, config);
    return data;
  },

  async deleteVoucher({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/vouchers/${id}`, config);
    return data;
  },

  async getVouchers({ page, size, query, sort }: { page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<VoucherResponse>> {
    const { data } = await api.get('/api/v1/vouchers', { params: { page, size, query, sort }, ...config });
    return data;
  },

  async createVoucher({ body }: { body: CreateVoucherRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/vouchers', body, config);
    return data;
  },

  async getVoucherByCode({ code }: { code: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VoucherResponse>> {
    const { data } = await api.get('/api/v1/vouchers/code', { params: { code }, ...config });
    return data;
  },
};

// ── OrderService ──────────────────────────────────────────────
export const OrderService = {

  async cancelOrder({ orderId }: { orderId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.put(`/api/v1/orders/${orderId}/cancel`, undefined, config);
    return data;
  },

  async getOrders({ page, size, query, sort }: { page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<OrderDetailResponse>> {
    const { data } = await api.get('/api/v1/orders', { params: { page, size, query, sort }, ...config });
    return data;
  },

  async createOrder({ body }: { body: CreateOrderRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderResponse>> {
    const { data } = await api.post('/api/v1/orders', body, config);
    return data;
  },

  async getOrderById({ orderId }: { orderId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<OrderDetailResponse>> {
    const { data } = await api.get(`/api/v1/orders/${orderId}`, config);
    return data;
  },
};

// ── EnrollmentService ──────────────────────────────────────────────
export const EnrollmentService = {

  async checkEnrollmentStatus({ body }: { body: string[] }, config?: AxiosRequestConfig): Promise<ApiResponse<CheckEnrollmentStatus>> {
    const { data } = await api.post('/api/v1/enrollments/check', body, config);
    return data;
  },

  async getEnrolledCourses({ page, size }: { page?: number; size?: number }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CourseResponse>> {
    const { data } = await api.get('/api/v1/enrollments', { params: { page, size }, ...config });
    return data;
  },
};

// ── StatisticsService ──────────────────────────────────────────────
export const StatisticsService = {

  /** Get yearly instructor statistics */
  async getInstructorYearlyOverview({ year }: { year?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorStatisticsResponse>> {
    const { data } = await api.get('/api/v1/statistics/instructor/overview/yearly', { params: { year }, ...config });
    return data;
  },

  /** Get range instructor statistics */
  async getInstructorRangeOverview({ startDate, endDate }: { startDate: string; endDate: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorStatisticsResponse>> {
    const { data } = await api.get('/api/v1/statistics/instructor/overview/range', { params: { startDate, endDate }, ...config });
    return data;
  },

  /** Get monthly instructor statistics */
  async getInstructorMonthlyOverview({ year, month }: { year: number; month: number }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorStatisticsResponse>> {
    const { data } = await api.get('/api/v1/statistics/instructor/overview/monthly', { params: { year, month }, ...config });
    return data;
  },

  /** Get course specific statistics */
  async getCourseStatistics({ courseId, year, month, startDate, endDate }: { courseId: string; year?: number; month?: number; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseStatisticsResponse>> {
    const { data } = await api.get(`/api/v1/statistics/instructor/courses/${courseId}`, { params: { year, month, startDate, endDate }, ...config });
    return data;
  },

  /** Get dashboard metrics */
  async getDashboardMetrics({ year, month }: { year?: number; month?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<DashboardMetricsResponse>> {
    const { data } = await api.get('/api/v1/statistics/dashboard', { params: { year, month }, ...config });
    return data;
  },

  /** Get admin yearly overview */
  async getAdminYearlyOverview({ year }: { year?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<AdminOverviewResponse>> {
    const { data } = await api.get('/api/v1/statistics/admin/overview/yearly', { params: { year }, ...config });
    return data;
  },

  /** Get admin range overview */
  async getAdminRangeOverview({ startDate, endDate }: { startDate: string; endDate: string }, config?: AxiosRequestConfig): Promise<ApiResponse<AdminOverviewResponse>> {
    const { data } = await api.get('/api/v1/statistics/admin/overview/range', { params: { startDate, endDate }, ...config });
    return data;
  },

  /** Get admin monthly overview */
  async getAdminMonthlyOverview({ year, month }: { year: number; month: number }, config?: AxiosRequestConfig): Promise<ApiResponse<AdminOverviewResponse>> {
    const { data } = await api.get('/api/v1/statistics/admin/overview/monthly', { params: { year, month }, ...config });
    return data;
  },

  /** Get admin instructor revenue */
  async getInstructorRevenue({ instructorId, months }: { instructorId: string; months?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<InstructorRevenueResponse>> {
    const { data } = await api.get(`/api/v1/statistics/admin/instructors/${instructorId}/revenue`, { params: { months }, ...config });
    return data;
  },
};

// ── AdminEnrollmentService ──────────────────────────────────────────────
export const AdminEnrollmentService = {

  async getUserSummary({ userId }: { userId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserEnrollmentSummaryResponse>> {
    const { data } = await api.get(`/api/v1/enrollments/admin/users/${userId}/summary`, config);
    return data;
  },
};
