// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
    ApiResponse,
    AssignmentSubmissionResponse,
    CertificateRequestResponse,
    ChooseQuizAnswerRequest,
    CourseProgressResponse,
    CoursesProgressSummaryResponse,
    CreateAssignmentSubmissionRequest,
    CreateVideoNoteRequest,
    DailyGoalResponse,
    GradeEssayRequest,
    InVideoAssessmentSubmissionResponse,
    LearningActivityByMonthResponse,
    LearningActivityRequest,
    LearningItemProgressResponse,
    LearningPathRequest,
    LearningPathResponse,
    PaginatedApiResponse,
    QuizQuestionAnalyticsResponse,
    QuizSessionQuestionResponse,
    QuizSessionResponse,
    SetDailyGoalRequest,
    SubmitQuizSessionRequest,
    SubmitVideoQuestionRequest,
    TrackingVideoLessonRequest,
    UpdateVideoNoteRequest,
    UserLearningSummaryResponse,
    UserStreakResponse,
    VideoLessonTrackingHistoryResponse,
    VideoNoteDto,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── VideoNoteService ──────────────────────────────────────────────
export const VideoNoteService = {

    async updateNote({ noteId, body }: { noteId: string; body: UpdateVideoNoteRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoNoteDto>> {
        const { data } = await api.put(`/api/v1/learning/video-notes/${noteId}`, body, config);
        return data;
    },

    async deleteNote({ noteId }: { noteId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.delete(`/api/v1/learning/video-notes/${noteId}`, config);
        return data;
    },

    async getNotesByLesson({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoNoteDto>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-notes`, config);
        return data;
    },

    async createNote({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: CreateVideoNoteRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoNoteDto>> {
        const { data } = await api.post(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-notes`, body, config);
        return data;
    },

    async getNotesByCourse({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoNoteDto>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/video-notes`, config);
        return data;
    },
};

// ── DailyGoalService ──────────────────────────────────────────────
export const DailyGoalService = {

    /** Get current user's daily goals for a specific date */
    async getDailyGoals({ date }: { date?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<DailyGoalResponse>> {
        const { data } = await api.get('/api/v1/daily-goals', { params: { date }, ...config });
        return data;
    },

    /** Edit current user's daily goal target */
    async editDailyGoal({ body }: { body: SetDailyGoalRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<DailyGoalResponse>> {
        const { data } = await api.put('/api/v1/daily-goals', body, config);
        return data;
    },

    /** Set current user's daily goal target */
    async setDailyGoal({ body }: { body: SetDailyGoalRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<DailyGoalResponse>> {
        const { data } = await api.post('/api/v1/daily-goals', body, config);
        return data;
    },

    /** Delete current user's daily goal for a specific date */
    async deleteDailyGoal({ date, goalType, targetItemId }: { date?: string; goalType: string; targetItemId?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.delete('/api/v1/daily-goals', { params: { date, goalType, targetItemId }, ...config });
        return data;
    },

    /** Get current user's daily goals for a specific month */
    async getDailyGoalsInMonth({ year, month }: { year: number; month: number }, config?: AxiosRequestConfig): Promise<ApiResponse<DailyGoalResponse>> {
        const { data } = await api.get('/api/v1/daily-goals/month', { params: { year, month }, ...config });
        return data;
    },
};

// ── CertificateService ──────────────────────────────────────────────
export const CertificateService = {

    /** Reject certificate request (For Instructor) */
    async rejectCertificate({ requestId }: { requestId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CertificateRequestResponse>> {
        const { data } = await api.put(`/api/v1/certificates/requests/${requestId}/reject`, undefined, config);
        return data;
    },

    /** Approve certificate request (For Instructor) */
    async approveCertificate({ requestId }: { requestId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CertificateRequestResponse>> {
        const { data } = await api.put(`/api/v1/certificates/requests/${requestId}/approve`, undefined, config);
        return data;
    },

    /** Apply for course certificate */
    async applyForCertificate({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CertificateRequestResponse>> {
        const { data } = await api.post(`/api/v1/certificates/apply/${courseId}`, undefined, config);
        return data;
    },

    /** Get all certificate requests */
    async getAllRequests({ status, page, size, query, sort }: { status?: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CertificateRequestResponse>> {
        const { data } = await api.get('/api/v1/certificates/requests', { params: { status, page, size, query, sort }, ...config });
        return data;
    },

    /** Get certificate requests by course ID (For Instructor) */
    async getRequestsByCourse({ courseId, status, page, size, query, sort }: { courseId: string; status?: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<CertificateRequestResponse>> {
        const { data } = await api.get(`/api/v1/certificates/requests/${courseId}`, { params: { status, page, size, query, sort }, ...config });
        return data;
    },

    /** Get all user certificates */
    async getMyCertificates(config?: AxiosRequestConfig): Promise<ApiResponse<CertificateRequestResponse>> {
        const { data } = await api.get('/api/v1/certificates/my-certificates', config);
        return data;
    },

    /** Get user certificate by course */
    async getMyCertificate({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CertificateRequestResponse>> {
        const { data } = await api.get(`/api/v1/certificates/my-certificate/${courseId}`, config);
        return data;
    },
};

// ── QuizSessionService ──────────────────────────────────────────────
export const QuizSessionService = {

    /** Grade essay questions in a PENDING_GRADE quiz session */
    async gradeEssay({ sessionId, body }: { sessionId: string; body: GradeEssayRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizSessionResponse>> {
        const { data } = await api.post(`/api/v1/learning/quiz-sessions/${sessionId}/grade-essay`, body, config);
        return data;
    },

    async submitQuizSession({ quizSessionId, body }: { quizSessionId: string; body: SubmitQuizSessionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizSessionResponse>> {
        const { data } = await api.post(`/api/v1/learning/quiz-sessions/${quizSessionId}/submit`, body, config);
        return data;
    },

    async chooseQuizSessionQuestion({ quizSessionId, body }: { quizSessionId: string; body: ChooseQuizAnswerRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post(`/api/v1/learning/quiz-sessions/${quizSessionId}/choose`, body, config);
        return data;
    },

    async createQuizSession({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizSessionResponse>> {
        const { data } = await api.post(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/quiz-sessions`, undefined, config);
        return data;
    },

    async getQuizSession({ quizSessionId }: { quizSessionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizSessionResponse>> {
        const { data } = await api.get(`/api/v1/learning/quiz-sessions/${quizSessionId}`, config);
        return data;
    },

    async getQuizSessionQuestions({ quizSessionId, page, size, query, sort }: { quizSessionId: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<QuizSessionQuestionResponse>> {
        const { data } = await api.get(`/api/v1/learning/quiz-sessions/${quizSessionId}/questions`, { params: { page, size, query, sort }, ...config });
        return data;
    },

    async getQuizSessions({ lessonId, userId, page, size, query, sort }: { lessonId: string; userId?: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<QuizSessionResponse>> {
        const { data } = await api.get(`/api/v1/learning/lessons/${lessonId}/quiz-sessions`, { params: { userId, page, size, query, sort }, ...config });
        return data;
    },

    /** Get analytical statistics for a quiz */
    async getQuizAnalytics({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuizQuestionAnalyticsResponse>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/quiz-sessions/analytics`, config);
        return data;
    },
};

// ── VideoTrackingService ──────────────────────────────────────────────
export const VideoTrackingService = {

    async getVideoLessonTrackingHistories({ courseId, lessonId, page, size, query, sort }: { courseId: string; lessonId: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<VideoLessonTrackingHistoryResponse>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-tracking`, { params: { page, size, query, sort }, ...config });
        return data;
    },

    async trackVideoProgress({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: TrackingVideoLessonRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-tracking`, body, config);
        return data;
    },

    async submitVideoQuestionAnswer({ courseId, lessonId, body }: { courseId: string; lessonId: string; body: SubmitVideoQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-tracking/questions/submit`, body, config);
        return data;
    },

    async getVideoQuestionSubmissions({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<InVideoAssessmentSubmissionResponse>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-tracking/submissions`, config);
        return data;
    },

    async getVideoLessonTrackingHistory({ courseId, lessonId }: { courseId: string; lessonId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<VideoLessonTrackingHistoryResponse>> {
        const { data } = await api.get(`/api/v1/learning/courses/${courseId}/lessons/${lessonId}/video-tracking/history`, config);
        return data;
    },
};

// ── LearningProgressService ──────────────────────────────────────────────
export const LearningProgressService = {

    /** Mark an item as complete (e.g. Article) */
    async markItemAsComplete({ itemId }: { itemId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post(`/api/v1/learning/course-progress/items/${itemId}/complete`, undefined, config);
        return data;
    },

    async getCourseProgressByCourseIds({ courseIds }: { courseIds: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseProgressResponse>> {
        const { data } = await api.get('/api/v1/learning/course-progress', { params: { courseIds }, ...config });
        return data;
    },

    async getMyCourseProgress({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseProgressResponse>> {
        const { data } = await api.get(`/api/v1/learning/course-progress/${courseId}`, config);
        return data;
    },

    async getLearningItemProgressByCourseId({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<LearningItemProgressResponse>> {
        const { data } = await api.get(`/api/v1/learning/course-progress/${courseId}/items`, config);
        return data;
    },

    /** Get detailed progress of a student in a course */
    async getStudentProgress({ courseId, studentId }: { courseId: string; studentId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<LearningItemProgressResponse>> {
        const { data } = await api.get(`/api/v1/learning/course-progress/courses/${courseId}/students/${studentId}/progress`, config);
        return data;
    },

    /** Get overview progress of students in a course */
    async getCourseProgress({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseProgressResponse>> {
        const { data } = await api.get(`/api/v1/learning/course-progress/courses/${courseId}/progress`, config);
        return data;
    },
};

// ── AssignmentService ──────────────────────────────────────────────
export const AssignmentService = {

    async getAssignmentSubmission({ assignmentId }: { assignmentId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<AssignmentSubmissionResponse>> {
        const { data } = await api.get('/api/v1/learning/assignment-submissions', { params: { assignmentId }, ...config });
        return data;
    },

    async submitAssignment({ body, assignmentId }: { body: CreateAssignmentSubmissionRequest; assignmentId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post('/api/v1/learning/assignment-submissions', body, { params: { assignmentId }, ...config });
        return data;
    },

    async scoreAssignmentSubmission({ submissionId, score }: { submissionId: string; score: number }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post(`/api/v1/learning/assignment-submissions/${submissionId}/score`, undefined, { params: { score }, ...config });
        return data;
    },

    async getAssignmentSubmissions({ assignmentId, page, size, query, sort }: { assignmentId: string; page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<AssignmentSubmissionResponse>> {
        const { data } = await api.get('/api/v1/learning/assignment-submissions/list', { params: { assignmentId, page, size, query, sort }, ...config });
        return data;
    },

    async deleteAssignmentSubmission({ submissionId }: { submissionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.delete(`/api/v1/learning/assignment-submissions/${submissionId}`, config);
        return data;
    },
};

// ── LearningActivityService ──────────────────────────────────────────────
export const LearningActivityService = {

    /** Record learning activity heartbeat */
    async recordActivity({ body }: { body: LearningActivityRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.post('/api/v1/learning/activity', body, config);
        return data;
    },
};

// ── LearningPathService ──────────────────────────────────────────────
export const LearningPathService = {

    async getLearningPaths(config?: AxiosRequestConfig): Promise<ApiResponse<LearningPathResponse>> {
        const { data } = await api.get('/api/v1/learning-paths', config);
        return data;
    },

    async createLearningPath({ body }: { body: LearningPathRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<LearningPathResponse>> {
        const { data } = await api.post('/api/v1/learning-paths', body, config);
        return data;
    },

    async getLearningPath({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<LearningPathResponse>> {
        const { data } = await api.get(`/api/v1/learning-paths/${id}`, config);
        return data;
    },

    async getActiveLearningPath(config?: AxiosRequestConfig): Promise<ApiResponse<LearningPathResponse>> {
        const { data } = await api.get('/api/v1/learning-paths/active', config);
        return data;
    },

    async dropActiveLearningPath(config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
        const { data } = await api.delete('/api/v1/learning-paths/active', config);
        return data;
    },
};

// ── StreakService ──────────────────────────────────────────────
export const StreakService = {

    async getMyStreak(config?: AxiosRequestConfig): Promise<ApiResponse<UserStreakResponse>> {
        const { data } = await api.get('/api/v1/streaks/me', config);
        return data;
    },
};

// ── AdminLearningService ──────────────────────────────────────────────
export const AdminLearningService = {

    async getUserSummary({ userId }: { userId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserLearningSummaryResponse>> {
        const { data } = await api.get(`/api/v1/learning/admin/users/${userId}/summary`, config);
        return data;
    },

    async getUserCourseProgress({ userId, courseIds }: { userId: string; courseIds: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseProgressResponse>> {
        const { data } = await api.get(`/api/v1/learning/admin/users/${userId}/course-progress`, { params: { courseIds }, ...config });
        return data;
    },

    async getUserActivity({ userId, months }: { userId: string; months?: number }, config?: AxiosRequestConfig): Promise<ApiResponse<LearningActivityByMonthResponse>> {
        const { data } = await api.get(`/api/v1/learning/admin/users/${userId}/activity`, { params: { months }, ...config });
        return data;
    },

    async getCoursesProgressSummary({ courseIds }: { courseIds: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CoursesProgressSummaryResponse>> {
        const { data } = await api.get('/api/v1/learning/admin/courses/progress-summary', { params: { courseIds }, ...config });
        return data;
    },
};
