// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  PaginatedApiResponse,
} from '@/types';
import type {
  UserNotificationResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── NotificationService ──────────────────────────────────────────────
export const NotificationService = {

  async toggleRead({ notificationId }: { notificationId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/notifications/${notificationId}/toggle-read`, undefined, config);
    return data;
  },

  /** Test Push Notification */
  async testPushNotification({ title, body }: { title: string; body: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/notifications/test-push', undefined, { params: { title, body }, ...config });
    return data;
  },

  async testInAppNotification({ userId, title, body }: { userId: string; title: string; body: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/notifications/test-in-app', undefined, { params: { userId, title, body }, ...config });
    return data;
  },

  async markAllAsUnread(config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/notifications/mark-all-unread', undefined, config);
    return data;
  },

  async markAllAsRead(config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/notifications/mark-all-read', undefined, config);
    return data;
  },

  async getNotifications({ page, size, query, sort }: { page?: number; size?: number; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<UserNotificationResponse>> {
    const { data } = await api.get('/api/v1/notifications', { params: { page, size, query, sort }, ...config });
    return data;
  },

  async countUnreadNotifications(config?: AxiosRequestConfig): Promise<ApiResponse<number>> {
    const { data } = await api.get('/api/v1/notifications/unread-count', config);
    return data;
  },

  async deleteNotification({ notificationId }: { notificationId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/notifications/${notificationId}`, config);
    return data;
  },
};
