// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  PaginatedApiResponse,
} from '@/types';
import type {
  AddToWishlistRequest,
  AnswerDto,
  CourseQnAStatisticsResponse,
  CreateAnswerRequest,
  CreateQnAReportRequest,
  CreateQuestionRequest,
  CreateReportReviewRequest,
  CreateReviewReactionRequest,
  CreateReviewReplyRequest,
  CreateReviewRequest,
  QuestionDto,
  Report,
  ReportStatisticsOverviewResponse,
  ReviewResponse,
  ReviewStatisticsResponse,
  UpdateAnswerRequest,
  UpdateQuestionRequest,
  UpdateReviewReplyRequest,
  UpdateReviewRequest,
  WishlistItemResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── ReviewService ──────────────────────────────────────────────
export const ReviewService = {

  async updateReview({ reviewId, body }: { reviewId: string; body: UpdateReviewRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/reviews/${reviewId}`, body, config);
    return data;
  },

  async deleteReview({ reviewId }: { reviewId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/reviews/${reviewId}`, config);
    return data;
  },

  /** Update review reply (Instructor only) */
  async updateReviewReply({ replyId, body }: { replyId: string; body: UpdateReviewReplyRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put(`/api/v1/reviews/replies/${replyId}`, body, config);
    return data;
  },

  /** Delete review reply (Instructor only) */
  async deleteReviewReply({ replyId }: { replyId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/reviews/replies/${replyId}`, config);
    return data;
  },

  async getReviewsByCourseId({ courseId, page, size, sort }: { courseId: string; page?: number; size?: number; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<ReviewResponse>> {
    const { data } = await api.get('/api/v1/reviews', { params: { courseId, page, size, sort }, ...config });
    return data;
  },

  async createReview({ body }: { body: CreateReviewRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/reviews', body, config);
    return data;
  },

  async reportReview({ reviewId, body }: { reviewId: string; body: CreateReportReviewRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/reviews/${reviewId}/report`, body, config);
    return data;
  },

  /** Reply to review (Instructor only) */
  async createReviewReply({ reviewId, body }: { reviewId: string; body: CreateReviewReplyRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/reviews/${reviewId}/replies`, body, config);
    return data;
  },

  async reactReview({ reviewId, body }: { reviewId: string; body: CreateReviewReactionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/reviews/${reviewId}/react`, body, config);
    return data;
  },
};

// ── CourseQnAService ──────────────────────────────────────────────
export const CourseQnAService = {

  async getQuestionById({ questionId }: { questionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<QuestionDto>> {
    const { data } = await api.get(`/api/v1/course-qna/questions/${questionId}`, config);
    return data;
  },

  async updateQuestion({ questionId, body }: { questionId: string; body: UpdateQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuestionDto>> {
    const { data } = await api.put(`/api/v1/course-qna/questions/${questionId}`, body, config);
    return data;
  },

  async deleteQuestion({ questionId }: { questionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/course-qna/questions/${questionId}`, config);
    return data;
  },

  async updateAnswer({ answerId, body }: { answerId: string; body: UpdateAnswerRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<AnswerDto>> {
    const { data } = await api.put(`/api/v1/course-qna/answers/${answerId}`, body, config);
    return data;
  },

  async deleteAnswer({ answerId }: { answerId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/course-qna/answers/${answerId}`, config);
    return data;
  },

  async getQuestions({ courseId, lessonId, page, size, sort }: { courseId: string; lessonId?: string; page?: number; size?: number; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<QuestionDto>> {
    const { data } = await api.get('/api/v1/course-qna/questions', { params: { courseId, lessonId, page, size, sort }, ...config });
    return data;
  },

  async createQuestion({ body }: { body: CreateQuestionRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<QuestionDto>> {
    const { data } = await api.post('/api/v1/course-qna/questions', body, config);
    return data;
  },

  async upvoteQuestion({ questionId }: { questionId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/course-qna/questions/${questionId}/upvote`, undefined, config);
    return data;
  },

  async reportQuestion({ questionId, body }: { questionId: string; body: CreateQnAReportRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/course-qna/questions/${questionId}/report`, body, config);
    return data;
  },

  async createAnswer({ body }: { body: CreateAnswerRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<AnswerDto>> {
    const { data } = await api.post('/api/v1/course-qna/answers', body, config);
    return data;
  },

  async upvoteAnswer({ answerId }: { answerId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/course-qna/answers/${answerId}/upvote`, undefined, config);
    return data;
  },

  async reportAnswer({ answerId, body }: { answerId: string; body: CreateQnAReportRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/course-qna/answers/${answerId}/report`, body, config);
    return data;
  },

  async getAnswersForQuestion({ questionId, page, size, sort }: { questionId: string; page?: number; size?: number; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<AnswerDto>> {
    const { data } = await api.get(`/api/v1/course-qna/questions/${questionId}/answers`, { params: { page, size, sort }, ...config });
    return data;
  },

  async getReplies({ answerId, page, size, sort }: { answerId: string; page?: number; size?: number; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<AnswerDto>> {
    const { data } = await api.get(`/api/v1/course-qna/answers/${answerId}/replies`, { params: { page, size, sort }, ...config });
    return data;
  },
};

// ── WishlistService ──────────────────────────────────────────────
export const WishlistService = {

  async getWishlist(config?: AxiosRequestConfig): Promise<ApiResponse<WishlistItemResponse[]>> {
    const { data } = await api.get('/api/v1/wishlist', config);
    return data;
  },

  async addToWishlist({ body }: { body: AddToWishlistRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/wishlist', body, config);
    return data;
  },

  async removeFromWishlist({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete('/api/v1/wishlist', { params: { courseId }, ...config });
    return data;
  },
};

// ── SocialStatisticsService ──────────────────────────────────────────────
export const SocialStatisticsService = {

  /** Get course review statistics */
  async getReviewStatistics({ courseId }: { courseId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<ReviewStatisticsResponse>> {
    const { data } = await api.get(`/api/v1/reviews/statistics/courses/${courseId}`, config);
    return data;
  },

  /** Get report statistics overview */
  async getReportOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<ReportStatisticsOverviewResponse>> {
    const { data } = await api.get('/api/v1/reports/statistics/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },

  /** Get course QnA statistics */
  async getCourseQnAStatistics({ courseId, groupBy, startDate, endDate }: { courseId: string; groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<CourseQnAStatisticsResponse>> {
    const { data } = await api.get(`/api/v1/course-qna/statistics/courses/${courseId}`, { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },
};

// ── AdminReportService ──────────────────────────────────────────────
export const AdminReportService = {

  async getReports({ type, page, size, sort }: { type?: string; page?: number; size?: number; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<Report>> {
    const { data } = await api.get('/api/v1/reports', { params: { type, page, size, sort }, ...config });
    return data;
  },

  async dismissReport({ reportId }: { reportId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/reports/${reportId}/dismiss`, config);
    return data;
  },

  async deleteReportedContent({ reportId }: { reportId: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.delete(`/api/v1/reports/${reportId}/content`, config);
    return data;
  },
};
