// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  PaginatedApiResponse,
} from '@/types';
import type {
  CreatePolicyRequest,
  DeviceTokenRequest,
  PolicyDetailResponse,
  PolicySummaryResponse,
  PresignedUrlResponse,
  TerminatePartnershipRequest,
  UpdatePolicyRequest,
  UpdatePreferredCategoriesRequest,
  UpdateProfileRequest,
  UserDto,
  UserStatisticsOverviewResponse,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── UserService ──────────────────────────────────────────────
export const UserService = {

  /** Get user by ID */
  async getUserById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.get(`/api/v1/users/${id}`, config);
    return data;
  },

  /** Update user profile */
  async updateUser({ id, body }: { id: string; body: UpdateProfileRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.put(`/api/v1/users/${id}`, body, config);
    return data;
  },

  /** Update preferred categories */
  async updatePreferredCategories({ body }: { body: UpdatePreferredCategoriesRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.put('/api/v1/users/me/preferred-categories', body, config);
    return data;
  },

  /** Approve instructor (admin) */
  async verifyInstructor({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/users/${id}/verify-instructor`, undefined, config);
    return data;
  },

  /** Terminate partnership with instructor (admin) */
  async terminatePartnership({ id, body }: { id: string; body: TerminatePartnershipRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/users/${id}/terminate-partnership`, body, config);
    return data;
  },

  /** Reject instructor (admin) */
  async rejectInstructor({ id, reason }: { id: string; reason: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/users/${id}/reject-instructor`, undefined, { params: { reason }, ...config });
    return data;
  },

  /** Save FCM device token */
  async saveDeviceToken({ body }: { body: DeviceTokenRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/users/device-tokens', body, config);
    return data;
  },

  /** List all users (admin) */
  async getAllUsers({ page, size, query, sort, role, isInstructorVerified }: { page?: number; size?: number; query?: string; sort?: string; role?: string; isInstructorVerified?: boolean }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<UserDto>> {
    const { data } = await api.get('/api/v1/users', { params: { page, size, query, sort, role, isInstructorVerified }, ...config });
    return data;
  },

  /** Get current user profile */
  async getCurrentUser(config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.get('/api/v1/users/me', config);
    return data;
  },
};

// ── PolicyService ──────────────────────────────────────────────
export const PolicyService = {

  /** Update policy draft */
  async updatePolicyDraft({ id, body }: { id: string; body: UpdatePolicyRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.put(`/api/v1/policies/${id}`, body, config);
    return data;
  },

  async getPublishedPolicies(config?: AxiosRequestConfig): Promise<ApiResponse<PolicySummaryResponse[]>> {
    const { data } = await api.get('/api/v1/policies', config);
    return data;
  },

  /** Create policy draft */
  async createPolicyDraft({ body }: { body: CreatePolicyRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.post('/api/v1/policies', body, config);
    return data;
  },

  /** Publish policy draft */
  async publishPolicy({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.post(`/api/v1/policies/${id}/publish`, undefined, config);
    return data;
  },

  /** Archive policy */
  async archivePolicy({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.post(`/api/v1/policies/${id}/archive`, undefined, config);
    return data;
  },

  async getPublishedPolicy({ slug }: { slug: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.get(`/api/v1/policies/${slug}`, config);
    return data;
  },

  /** List policy versions */
  async getPolicyVersions({ page, size, status, policyType, query, sort }: { page?: number; size?: number; status?: string; policyType?: string; query?: string; sort?: string }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<PolicySummaryResponse>> {
    const { data } = await api.get('/api/v1/policies/versions', { params: { page, size, status, policyType, query, sort }, ...config });
    return data;
  },

  /** Get policy detail by ID (admin) */
  async getPolicyDetail({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PolicyDetailResponse>> {
    const { data } = await api.get(`/api/v1/policies/detail/${id}`, config);
    return data;
  },
};

// ── PresignedUrlService ──────────────────────────────────────────────
export const PresignedUrlService = {

  /** Get presigned URL for avatar upload */
  async getPresignedUrl({ fileName, contentType }: { fileName: string; contentType: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PresignedUrlResponse>> {
    const { data } = await api.get('/api/v1/users/upload/presigned-url', { params: { fileName, contentType }, ...config });
    return data;
  },
};

// ── UserStatisticsService ──────────────────────────────────────────────
export const UserStatisticsService = {

  /** Get user statistics overview */
  async getOverview({ groupBy, startDate, endDate }: { groupBy?: string; startDate?: string; endDate?: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserStatisticsOverviewResponse>> {
    const { data } = await api.get('/api/v1/users/statistics/overview', { params: { groupBy, startDate, endDate }, ...config });
    return data;
  },
};
