// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { AxiosRequestConfig } from 'axios';
import { api } from '@/lib/axios';

import type {
  ApiResponse,
  DeviceTokenRequest,
  PaginatedApiResponse,
  PresignedUrlResponse,
  UpdateProfileRequest,
  UserDto,
} from '@/types';

// ─────────────────────────────────────────────────────────────────

// ── UserService ──────────────────────────────────────────────
export const UserService = {

  /** Get user by ID */
  async getUserById({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.get(`/api/v1/users/${id}`, config);
    return data;
  },

  /** Update user profile */
  async updateUser({ id, body }: { id: string; body: UpdateProfileRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.put(`/api/v1/users/${id}`, body, config);
    return data;
  },

  /** Approve instructor (admin) */
  async verifyInstructor({ id }: { id: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/users/${id}/verify-instructor`, undefined, config);
    return data;
  },

  /** Reject instructor (admin) */
  async rejectInstructor({ id, reason }: { id: string; reason: string }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post(`/api/v1/users/${id}/reject-instructor`, undefined, { params: { reason }, ...config });
    return data;
  },

  /** Save FCM device token */
  async saveDeviceToken({ body }: { body: DeviceTokenRequest }, config?: AxiosRequestConfig): Promise<ApiResponse<Record<string, unknown>>> {
    const { data } = await api.post('/api/v1/users/device-tokens', body, config);
    return data;
  },

  /** List all users (admin) */
  async getAllUsers({ page, size, query, sort, role, isInstructorVerified }: { page?: number; size?: number; query?: string; sort?: string; role?: string; isInstructorVerified?: boolean }, config?: AxiosRequestConfig): Promise<PaginatedApiResponse<UserDto>> {
    const { data } = await api.get('/api/v1/users', { params: { page, size, query, sort, role, isInstructorVerified }, ...config });
    return data;
  },

  /** Get current user profile */
  async getCurrentUser(config?: AxiosRequestConfig): Promise<ApiResponse<UserDto>> {
    const { data } = await api.get('/api/v1/users/me', config);
    return data;
  },
};

// ── PresignedUrlService ──────────────────────────────────────────────
export const PresignedUrlService = {

  /** Get presigned URL for avatar upload */
  async getPresignedUrl({ fileName, contentType }: { fileName: string; contentType: string }, config?: AxiosRequestConfig): Promise<ApiResponse<PresignedUrlResponse>> {
    const { data } = await api.get('/api/v1/users/upload/presigned-url', { params: { fileName, contentType }, ...config });
    return data;
  },
};
