// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

// ── Domain types ───────────────────────────────────────────────


export interface UserNotificationResponse {
  id?: string;
  userId?: string;
  title?: string;
  message?: string;
  type?: string;
  referenceId?: string;
  actionUrl?: string;
  metadata?: Record<string, Record<string, unknown>>;
  isRead?: boolean;
  sentAt?: string;
}
