// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

// ── Generic wrapper types (shared, not prefixed) ──────────────

export interface ApiResponse<T> {
  success?: boolean;
  message?: string;
  data?: T;
}

export interface PaginatedApiResponse<T> {
  success?: boolean;
  message?: string;
  data?: T[];
  meta?: PaginatedMetadata;
}

export interface PaginatedMetadata {
  page?: number;
  limit?: number;
  totalElements?: number;
  totalPages?: number;
}
