// =============================================================
// AUTO-GENERATED by swagger-ts-codegen
// DO NOT EDIT MANUALLY — regenerate from the OpenAPI spec
// =============================================================

import type { StatisticsByTimeResponse } from "./courseApi";

// ── Domain types ───────────────────────────────────────────────

export interface UpdateProfileRequest {
  name: string;
  gender?: "MALE" | "FEMALE";
  phoneNumber?: string;
  bio?: string;
  isReceivePushNotification?: boolean;
  avatarFileKey?: string;
  cvFileKey?: string;
}

export interface UserDto {
  userId?: string;
  name?: string;
  email?: string;
  role?: "USER" | "INSTRUCTOR" | "ADMIN";
  gender?: "MALE" | "FEMALE";
  isReceivePushNotification?: boolean;
  isInstructorVerified?: boolean;
  status?: "UNVERIFIED" | "ACTIVE" | "BANNED";
  avatarUrl?: string;
  phoneNumber?: string;
  bio?: string;
  xp?: number;
  cvUrl?: string;
  createdAt?: string;
  updatedAt?: string;
  lastAccessAt?: string;
  instructorVerifiedAt?: string;
  isPartnershipTerminated?: boolean;
}

export interface UpdatePreferredCategoriesRequest {
  categoryIds: string[];
}

export interface PolicySectionRequest {
  heading: string;
  anchor?: string;
  bodyMarkdown: string;
  orderIndex: number;
}

export interface UpdatePolicyRequest {
  policyType?: "PRIVACY" | "TERMS" | "REFUND" | "COOKIE" | "GENERAL";
  title: string;
  summary?: string;
  effectiveAt?: string;
  displayOrder?: number;
  sections: PolicySectionRequest[];
}

export interface PolicyDetailResponse {
  id?: string;
  policyType?: "PRIVACY" | "TERMS" | "REFUND" | "COOKIE" | "GENERAL";
  slug?: string;
  title?: string;
  summary?: string;
  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED";
  versionNumber?: number;
  effectiveAt?: string;
  publishedAt?: string;
  displayOrder?: number;
  sections?: PolicySectionResponse[];
}

export interface PolicySectionResponse {
  id?: string;
  heading?: string;
  anchor?: string;
  bodyMarkdown?: string;
  orderIndex?: number;
}

export interface DeviceTokenRequest {
  fcmToken: string;
  deviceInfo?: string;
}

export interface CreatePolicyRequest {
  policyType: "PRIVACY" | "TERMS" | "REFUND" | "COOKIE" | "GENERAL";
  slug: string;
  title: string;
  summary?: string;
  effectiveAt?: string;
  displayOrder?: number;
  sections: PolicySectionRequest[];
}

export interface PresignedUrlResponse {
  fileKey?: string;
  presignedUrl?: string;
}

export interface UserStatisticsOverviewResponse {
  newUsersInRange?: number;
  usersByRole?: Record<string, number>;
  instructorsByVerificationStatus?: Record<string, number>;
  newUsersByTime?: StatisticsByTimeResponse[];
  currentTotalUsers?: number;
}

export interface PolicySummaryResponse {
  id?: string;
  policyType?: "PRIVACY" | "TERMS" | "REFUND" | "COOKIE" | "GENERAL";
  slug?: string;
  title?: string;
  summary?: string;
  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED";
  versionNumber?: number;
  effectiveAt?: string;
  publishedAt?: string;
  displayOrder?: number;
}
